---
kind: pipeline
type: docker
name: proto

steps:
- name: lint_proto
  image: bufbuild/buf:0.26.0
  commands:
  - buf --version
  - buf check lint

---
kind: pipeline
type: docker
name: front_end_app

steps:
- name: build_proto
  image: davisvansant/grpc_web
  commands:
  - protoc --version
  - protoc -I=proto/hello/v1 hello.proto --js_out=import_style=commonjs,binary:./proto/output --grpc-web_out=import_style=typescript,mode=grpcwebtext:./proto/output

- name: app_install
  image: node:14.13.1
  commands:
  - node --version
  - cd front_end_app
  - npm install --verbose

- name: app_lint
  image: node:14.13.1
  depends_on:
  - app_install
  - build_proto
  commands:
  - node --version
  - cd front_end_app
  - npm run lint --verbose

- name: app_test
  image: node:14.13.1
  depends_on:
  - app_install
  - build_proto
  commands:
  - node --version
  - cd front_end_app
  - npm run test:unit --verbose

---
kind: pipeline
type: docker
name: front_end_server

steps:
- name: server_style
  image: rust:1.47.0
  environment:
    RUST_BACKTRACE: full
  commands:
  - rustup component add rustfmt
  - rustc --version
  - cargo --version
  - cargo fmt -- --version
  - cd front_end_server
  - cargo fmt --all -- --check

- name: server_lint
  image: rust:1.47.0
  environment:
    RUST_BACKTRACE: full
  commands:
  - rustup component add clippy
  - rustc --version
  - cargo --version
  - cargo clippy -- --version
  - cd front_end_server
  - cargo clippy

- name: server_test
  image: rust:1.47.0
  environment:
    RUST_BACKTRACE: full
  commands:
  - rustc --version
  - cargo --version
  - cd front_end_server
  - cargo test

---
kind: pipeline
type: docker
name: back_end_server

steps:
- name: server_style
  image: rust:1.47.0
  environment:
    RUST_BACKTRACE: full
  commands:
  - rustup component add rustfmt
  - rustc --version
  - cargo --version
  - cargo fmt -- --version
  - cd back_end_server
  - cargo fmt --all -- --check

- name: server_lint
  image: rust:1.47.0
  environment:
    RUST_BACKTRACE: full
  commands:
  - rustup component add clippy
  - rustup component add rustfmt
  - rustc --version
  - cargo --version
  - cargo clippy -- --version
  - cargo fmt -- --version
  - cd back_end_server
  - cargo clippy

- name: server_test
  image: rust:1.47.0
  environment:
    RUST_BACKTRACE: full
  commands:
  - rustup component add rustfmt
  - rustc --version
  - cargo --version
  - cargo fmt -- --version
  - cd back_end_server
  - cargo test

---
kind: pipeline
type: docker
name: build_front_end
depends_on:
- front_end_app
- front_end_server

steps:
- name: build_proto
  image: davisvansant/grpc_web
  commands:
  - protoc --version
  - protoc -I=proto/hello/v1 hello.proto --js_out=import_style=commonjs,binary:./proto/output --grpc-web_out=import_style=typescript,mode=grpcwebtext:./proto/output

- name: build_app
  image: node:14.13.1
  commands:
  - node --version
  - cd front_end_app
  - npm install
  - npm run build --verbose

- name: build_server
  image: rust:1.47.0
  environment:
    RUST_BACKTRACE: full
  commands:
  - rustup component add clippy
  - rustc --version
  - cargo --version
  - cd front_end_server
  - cargo build --release

- name: build_backend_server
  image: rust:1.47.0
  environment:
    RUST_BACKTRACE: full
  commands:
  - rustup component add rustfmt
  - rustc --version
  - cargo --version
  - cargo fmt -- --version
  - cd back_end_server
  - cargo build --release

- name: build_docker
  image: plugins/docker
  settings:
    dry_run: true
    dockerfile: ./docker/Dockerfile.front_end
    repo: davisvansant/grpc_web_front_end
    tags: 0.1.0

- name: build_docker_back_end
  image: plugins/docker
  settings:
    dry_run: true
    dockerfile: ./docker/Dockerfile.back_end
    repo: davisvansant/grpc_web_back_end
    tags: 0.1.0
