---
kind: pipeline
type: docker
name: proto

steps:
- name: lint
  image: bufbuild/buf:0.26.0
  commands:
  - buf --version
  - buf check lint

---
kind: pipeline
type: docker
name: front_end_app

steps:
- name: build_proto
  image: davisvansant/grpc_web
  commands:
  - protoc --version
  - protoc -I=proto/hello/v1 hello.proto --js_out=import_style=commonjs,binary:./proto/output --grpc-web_out=import_style=typescript,mode=grpcwebtext:./proto/output

- name: install
  image: node:14.13.1
  commands:
  - node --version
  - cd front_end_app
  - npm install --verbose

- name: lint
  image: node:14.13.1
  commands:
  - node --version
  - cd front_end_app
  - npm run lint --verbose

- name: test
  image: node:14.13.1
  commands:
  - node --version
  - cd front_end_app
  - npm run test:unit --verbose

---
kind: pipeline
type: docker
name: front_end_server

steps:
- name: style
  image: rust:1.47.0
  environment:
    RUST_BACKTRACE: full
  commands:
  - rustup component add rustfmt
  - rustc --version
  - cargo --version
  - cargo fmt -- --version
  - cd front_end_server
  - cargo fmt -- --check

- name: lint
  image: rust:1.47.0
  environment:
    RUST_BACKTRACE: full
  commands:
  - rustup component add clippy
  - rustc --version
  - cargo --version
  - cargo clippy -- --version
  - cd front_end_server
  - cargo clippy

- name: test
  image: rust:1.47.0
  environment:
    RUST_BACKTRACE: full
  commands:
  - rustc --version
  - cargo --version
  - cd front_end_server
  - cargo test

---
kind: pipeline
type: docker
name: back_end_server

steps:
- name: style
  image: rust:1.47.0
  environment:
    RUST_BACKTRACE: full
  commands:
  - rustup component add rustfmt
  - rustc --version
  - cargo --version
  - cargo fmt -- --version
  - cd back_end_server
  - cargo fmt -- --check

- name: lint
  image: rust:1.47.0
  environment:
    RUST_BACKTRACE: full
  commands:
  - rustup component add clippy
  - rustup component add rustfmt
  - rustc --version
  - cargo --version
  - cargo clippy -- --version
  - cargo fmt -- --version
  - cd back_end_server
  - cargo clippy

- name: test
  image: rust:1.47.0
  environment:
    RUST_BACKTRACE: full
  commands:
  - rustup component add rustfmt
  - rustc --version
  - cargo --version
  - cargo fmt -- --version
  - cd back_end_server
  - cargo test

---
kind: pipeline
type: docker
name: build
depends_on:
- front_end_app
- front_end_server
- back_end_server
trigger:
  event:
    - tag

steps:
- name: build_proto
  image: davisvansant/grpc_web
  commands:
  - protoc --version
  - protoc -I=proto/hello/v1 hello.proto --js_out=import_style=commonjs,binary:./proto/output --grpc-web_out=import_style=typescript,mode=grpcwebtext:./proto/output

- name: front_end_app
  image: node:14.13.1
  commands:
  - node --version
  - cd front_end_app
  - npm install
  - npm run build --verbose

- name: front_end_server
  image: rust:1.47.0
  environment:
    RUST_BACKTRACE: full
  commands:
  - rustup component add clippy
  - rustc --version
  - cargo --version
  - cd front_end_server
  - cargo build --release

- name: back_end_server
  image: rust:1.47.0
  environment:
    RUST_BACKTRACE: full
  commands:
  - rustup component add rustfmt
  - rustc --version
  - cargo --version
  - cargo fmt -- --version
  - cd back_end_server
  - cargo build --release

- name: docker_back_end
  image: plugins/docker
  settings:
    dry_run: true
    dockerfile: ./docker/Dockerfile.back_end
    repo: davisvansant/grpc_web_back_end
    tags: 0.1.0

- name: docker_envoy_proxy
  image: plugins/docker
  settings:
    dry_run: true
    dockerfile: ./docker/Dockerfile.envoy_proxy
    repo: davisvansant/grpc_web_envoy_proxy
    tags: 0.1.0

- name: docker_front_end
  image: plugins/docker
  settings:
    dry_run: true
    dockerfile: ./docker/Dockerfile.front_end
    repo: davisvansant/grpc_web_front_end
    tags: 0.1.0
