---
kind: pipeline
type: docker
name: default

steps:
- name: front_end_app - install
  image: node:14.13.1
  commands:
  - node --version
  - cd front_end_app
  - npm install --verbose

- name: front_end_app - lint
  image: node:14.13.1
  depends_on:
  - front_end_app - install
  commands:
  - node --version
  - cd front_end_app
  - npm run lint --verbose

- name: front_end_app - test
  image: node:14.13.1
  depends_on:
  - front_end_app - install
  commands:
  - node --version
  - cd front_end_app
  - npm run test:unit --verbose

- name: front_end_server - style
  image: rust:1.47.0
  environment:
    RUST_BACKTRACE: full
  commands:
  - rustup component add rustfmt
  - rustc --version
  - cargo --version
  - cargo fmt -- --version
  - cd front_end_server
  - cargo fmt --all -- --check

- name: front_end_server - lint
  image: rust:1.47.0
  environment:
    RUST_BACKTRACE: full
  commands:
  - rustup component add clippy
  - rustc --version
  - cargo --version
  - cargo clippy -- --version
  - cd front_end_server
  - cargo clippy --workspace --all-targets --all-features

- name: front_end_server - test
  image: rust:1.47.0
  environment:
    RUST_BACKTRACE: full
  depends_on:
  - front_end_server - style
  - front_end_server - lint
  commands:
  - rustc --version
  - cargo --version
  - cd front_end_server
  - cargo test --workspace --all-features --release
