---
kind: pipeline
type: docker
name: front_end_app

steps:
- name: app_install
  image: node:14.13.1
  commands:
  - node --version
  - cd front_end_app
  - npm install --verbose

- name: app_lint
  image: node:14.13.1
  depends_on:
  - app_install
  commands:
  - node --version
  - cd front_end_app
  - npm run lint --verbose

- name: app_test
  image: node:14.13.1
  depends_on:
  - app_install
  commands:
  - node --version
  - cd front_end_app
  - npm run test:unit --verbose

---
kind: pipeline
type: docker
name: front_end_server

steps:
- name: server_style
  image: rust:1.47.0
  environment:
    RUST_BACKTRACE: full
  commands:
  - rustup component add rustfmt
  - rustc --version
  - cargo --version
  - cargo fmt -- --version
  - cd front_end_server
  - cargo fmt --all -- --check

- name: server_lint
  image: rust:1.47.0
  environment:
    RUST_BACKTRACE: full
  commands:
  - rustup component add clippy
  - rustc --version
  - cargo --version
  - cargo clippy -- --version
  - cd front_end_server
  - cargo clippy

- name: server_test
  image: rust:1.47.0
  environment:
    RUST_BACKTRACE: full
  commands:
  - rustc --version
  - cargo --version
  - cd front_end_server
  - cargo test

---
kind: pipeline
type: docker
name: build_front_end
depends_on:
- front_end_app
- front_end_server

steps:
- name: build_app
  image: node:14.13.1
  commands:
  - node --version
  - cd front_end_app
  - npm install
  - npm run build --verbose

- name: build_server
  image: rust:1.47.0
  environment:
    RUST_BACKTRACE: full
  commands:
  - rustup component add clippy
  - rustc --version
  - cargo --version
  - cargo clippy -- --version
  - cd front_end_server
  - cargo build --release
